export const Footer = {
  footer: "volver a colecciones //",
  footerImg: require("../../../../assets/icons/introduccion/logo.png"),
};
export const PaginasMetal = [
  {
    id: "distrito_aluminio",
    titulo: "distrito aluminio //",
    imgL: require("../../../../assets/images/metal/distrito_aluminio.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/metal/distrito_aluminio_01.webp"),
    imgVid: require("../../../../assets/videos/distrito_aluminio.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "metal / metal", " "],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/en/colecciones/lava-iron",
    urlsiguiente: "/en/en/colecciones/distrito-marfil",
  },
  {
    id: "distrito_marfil",
    titulo: "distrito marfil //",
    imgL: require("../../../../assets/images/metal/distrito_marfil.webp"),
    img1: require("../../../../assets/images/metal/distrito_marfil_1.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    imgVid: require("../../../../assets/videos/distrito_marfil.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "metal / metal", " "],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/en/colecciones/distrito-aluminio",
    urlsiguiente: "/en/en/colecciones/lava-iron",
  },
  {
    id: "lava_iron",
    titulo: "lava iron //",
    imgL: require("../../../../assets/images/metal/lava_iron.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/metal/lava_iron_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/lava_iron.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "metal / metal", " "],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/en/colecciones/distrito-marfil",
    urlsiguiente: "/en/en/colecciones/distrito-aluminio",
  },
];
