import {
  MatSobre,
  MatBisel,
  MatMetal,
  // MatHaya,
} from "./MaterialModelos";
import {
  ModeloKirNoExt,
  ModeloKirExt,
  Emma,
  Connor,
  Gene,
  Grace,
  Harp,
  Hulk,
  Ilia,
  Kiff,
  Lyre,
  Mario,
  Olympus,
  Pisa,
  Progetto,
  Solo,
  Toyo,
  Victory,
} from "./Modelos";
//---------------------Collections------------------------
export const DatosConnor = {
  id: "Connor",
  modelo3d: Connor,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};

export const DatosEmma = {
  id: "Emma",
  modelo3d: Emma,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};

export const DatosGene = {
  id: "Gene",
  modelo3d: Gene,
  formasobre: "Barril",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosGrace = {
  id: "Grace",
  modelo3d: Grace,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosHarp = {
  id: "Harp",
  modelo3d: Harp,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosHulk = {
  id: "Hulk",
  modelo3d: Hulk,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosIlia = {
  id: "Ilia",
  modelo3d: Ilia,
  formasobre: "Barril",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosKiff = {
  id: "Kiff",
  modelo3d: Kiff,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosLyre = {
  id: "Lyre",
  modelo3d: Lyre,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosMario = {
  id: "Mario",
  modelo3d: Mario,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosOlympus = {
  id: "Olympus",
  modelo3d: Olympus,
  formasobre: "Circular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: false,
  circular: true,
  ovalado: false,
  barril: false,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosPisa = {
  id: "Pisa",
  modelo3d: Pisa,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosProgetto = {
  id: "Progetto",
  modelo3d: Progetto,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosSolo = {
  id: "Solo",
  modelo3d: Solo,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosToyo = {
  id: "Toyo",
  modelo3d: Toyo,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosVictory = {
  id: "Victory",
  modelo3d: Victory,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
//----------------------Life------------------------
export const DatosCollins = {
  id: "Collins",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
export const DatosFlip = {
  id: "Flip",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
export const DatosGibson = {
  id: "Gibson",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
export const DatosHakone = {
  id: "Hakone",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
export const DatosHemingway = {
  id: "Hemingway",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
export const DatosKir = {
  id: "Kir",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
export const DatosMary = {
  id: "Mary",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
export const DatosZama = {
  id: "Zama",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
//------------------------Contract------------------------
export const DatosBrezza = {
  id: "Brezza",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
export const DatosManhattan = {
  id: "Manhattan",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
export const DatosRob = {
  id: "Rob",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
export const DatosSpritz = {
  id: "Spritz",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
