import {
  MatSobre,
  MatBisel,
  MatMetal,
  MatFresno,
  MatHaya,
  // MatHaya,
} from "./MaterialModelos";
import {
  ModeloKirNoExt,
  ModeloKirExt,
  Emma,
  Connor,
  Gene,
  Grace,
  Harp,
  Hulk,
  Ilia,
  Kiff,
  Lyre,
  Mario,
  Olympus,
  Pisa,
  Progetto,
  Solo,
  Toyo,
  Victory,
  Collins,
  CollinsExt,
  Flip,
  FlipExt,
  Gibson,
  GibsonExt,
  Hakone,
  HakoneExt,
  Hemingway,
  HeminwayExt,
  Mary,
  MaryExt,
  Zama,
  ZamaExt,
  Brezza,
  BrezzaExt,
  Manhattan,
  Rob,
  Spritz,
  SprtizExt,
} from "./Modelos";
//---------------------Collections------------------------
export const DatosConnor = {
  id: "Connor",
  modelo3d: Connor,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};

export const DatosEmma = {
  id: "Emma",
  modelo3d: Emma,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};

export const DatosGene = {
  id: "Gene",
  modelo3d: Gene,
  formasobre: "Barril",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosGrace = {
  id: "Grace",
  modelo3d: Grace,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosHarp = {
  id: "Harp",
  modelo3d: Harp,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosHulk = {
  id: "Hulk",
  modelo3d: Hulk,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosIlia = {
  id: "Ilia",
  modelo3d: Ilia,
  formasobre: "Barril",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosKiff = {
  id: "Kiff",
  modelo3d: Kiff,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosLyre = {
  id: "Lyre",
  modelo3d: Lyre,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosMario = {
  id: "Mario",
  modelo3d: Mario,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosOlympus = {
  id: "Olympus",
  modelo3d: Olympus,
  formasobre: "Circular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: false,
  circular: true,
  ovalado: false,
  barril: false,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosPisa = {
  id: "Pisa",
  modelo3d: Pisa,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosProgetto = {
  id: "Progetto",
  modelo3d: Progetto,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosSolo = {
  id: "Solo",
  modelo3d: Solo,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosToyo = {
  id: "Toyo",
  modelo3d: Toyo,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosVictory = {
  id: "Victory",
  modelo3d: Victory,
  formasobre: "Rectangular",
  cambiasobre: true,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: true,
  barril: true,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatMetal[3],
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
//----------------------Life------------------------
export const DatosCollins = {
  id: "Collins",
  modelo3d: Collins,
  formasobre: "Barril",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: false,
  metal: false,
  fresno: true,
  haya: true,
  setMaterialSobre: MatSobre[7].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatHaya[3],
  extension: true,
  modeloExtension: CollinsExt,
};
export const DatosFlip = {
  id: "Flip",
  modelo3d: Flip,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: FlipExt,
};
export const DatosGibson = {
  id: "Gibson",
  modelo3d: Gibson,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[11].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatFresno[3],
  extension: true,
  modeloExtension: GibsonExt,
};
export const DatosHakone = {
  id: "Hakone",
  modelo3d: Hakone,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: HakoneExt,
};
export const DatosHemingway = {
  id: "Hemingway",
  modelo3d: Hemingway,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: false,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: HeminwayExt,
};
export const DatosKir = {
  id: "Kir",
  modelo3d: ModeloKirNoExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ModeloKirExt,
};
export const DatosMary = {
  id: "Mary",
  modelo3d: Mary,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: true,
  fresno: true,
  haya: true,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: MaryExt,
};
export const DatosZama = {
  id: "Zama",
  modelo3d: Zama,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: true,
  metal: false,
  fresno: true,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: true,
  modeloExtension: ZamaExt,
};
//------------------------Contract------------------------
export const DatosBrezza = {
  id: "Brezza",
  modelo3d: Brezza,
  formasobre: "Circular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: false,
  circular: true,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
  modeloExtension: BrezzaExt,
};
export const DatosManhattan = {
  id: "Manhattan",
  modelo3d: Manhattan,
  formasobre: "Circular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: true,
  ovalado: false,
  barril: false,
  bisel: true,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosRob = {
  id: "Rob",
  modelo3d: Rob,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosSpritz = {
  id: "Spritz80",
  modelo3d: Spritz,
  formasobre: "Cuadrado",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
export const DatosSpritz120 = {
  id: "Spritz120",
  modelo3d: SprtizExt,
  formasobre: "Rectangular",
  cambiasobre: false,
  cuadrado: false,
  rectangular: true,
  circular: false,
  ovalado: false,
  barril: false,
  bisel: false,
  bastidor: false,
  metal: true,
  fresno: false,
  haya: false,
  setMaterialSobre: MatSobre[4].imagen,
  setMaterialBisel: MatBisel[0].imagen,
  setMaterialBastidor: MatMetal[3],
  setMaterialPatas: MatMetal[3],
  extension: false,
};
