export const Footer = {
  footer: "volver a bath // return to bath",
  footerImg: require("../../../assets/icons/introduccion/logo.png"),
};

export const PaginasAcabado = [
  {
    id: "allure_anthracite",
    titulo: "allure anthracite //",
    imgL: require("../../../assets/images/piedra/allure_anthracite.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/piedra/allure_anthracite_01.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/allure_anthracite.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "piedra veteada / marble stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/bath/syrac",
    urlsiguiente: "/bath/beren-light-grey",
    pdfNombre: "Ficha-Técnica-ALLURE ANTHRACITE",
    pdfLink: "/downloads/Ficha-Técnica-ALLURE ANTHRACITE.pdf",
  },
  {
    id: "beren_light_grey",
    titulo: "beren light grey //",
    imgL: require("../../../assets/images/piedra/beren_light_grey.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/piedra/beren_light_grey_01.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/beren_light_grey.mp4"),
    desc: [
      "soft 1620x3240 mm/ 63”x127”",
      "caliza lusitana & catalana / lusitan & catalan limestone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/bath/allure-anthracite",
    urlsiguiente: "/bath/blanc-borghini",
    pdfNombre: "Ficha-Técnica-BEREN LIGHT GREY",
    pdfLink: "/downloads/Ficha-Técnica-BEREN LIGHT GREY.pdf",
  },
  {
    id: "blanc_borghini",
    titulo: "blanc borghini //",
    imgL: require("../../../assets/images/marmol/blanc_borghini.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/marmol/blanc_borghini_01.webp"),
    img2: require("../../../assets/images/marmol/blanc_borghini_02.webp"),
    imgVid: require("../../../assets/videos/blanc_borghini.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/bath/beren-light-grey",
    urlsiguiente: "/bath/blanc-invisible",
    pdfNombre: "Ficha-Técnica-BLANC BORGHINI",
    pdfLink: "/downloads/Ficha-Técnica-BLANC BORGHINI.pdf",
  },
  {
    id: "blanc_invisible",
    titulo: "blanc invisible //",
    imgL: require("../../../assets/images/marmol/blanc_invisible.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/marmol/blanc_invisible_01.webp"),
    imgVid: require("../../../assets/videos/blanc_invisible.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/bath/blanc-borghini",
    urlsiguiente: "/bath/brazil-super-white",
    pdfNombre: "Ficha-Técnica-BLANC INVISIBLE",
    pdfLink: "/downloads/Ficha-Técnica-BLANC INVISIBLE.pdf",
  },
  {
    id: "brazil_super_white",
    titulo: "brazil super white //",
    imgL: require("../../../assets/images/marmol/brazil_super_white.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    espesor2: require("../../../assets/icons/espesores/20mm.png"),
    img1: require("../../../assets/images/marmol/brazil_super_white_01.webp"),
    img2: require("../../../assets/images/marmol/brazil_super_white_02.webp"),
    imgVid: require("../../../assets/videos/brazil_super_white.mp4"),
    desc: [
      "hond 1600x3200 mm/ 63”x126”",
      "mármol / marble",
      "1 único diseño / 1 single design",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/bath/blanc-invisible",
    urlsiguiente: "/bath/calacatta",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "calacatta",
    titulo: "calacatta //",
    imgL: require("../../../assets/images/marmol/calacatta.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    espesor2: require("../../../assets/icons/espesores/20mm.png"),
    img1: require("../../../assets/images/marmol/calacatta_01.webp"),
    img2: require("../../../assets/images/marmol/calacatta_02.webp"),
    imgVid: require("../../../assets/videos/calacatta_pulido.mp4"),
    desc: [
      "natural s/r // pulido s/r 1620x3240 mm / 63,7”x127,5”",
      "mármol / marble stone",
      "",
    ],

    desc2: ["natural s/r 1600x3200 mm/ 63”x126”", "mármol / marble stone", ""],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/bath/brazil-super-white",
    urlsiguiente: "/bath/eme-light-grey",
    pdfNombre: "Ficha-Técnica-Calacata",
    pdfLink: "/downloads/Ficha-Técnica-Calacata.pdf",
  },
  {
    id: "eme_light_grey",
    titulo: "eme light grey //",
    imgL: require("../../../assets/images/piedra/eme_light_grey.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/piedra/eme_light_grey_01.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/eme_light_grey.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "piedra mediterránea / mediterranean stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/bath/calacatta",
    urlsiguiente: "/bath/kendo-classic",
    pdfNombre: "Ficha-Técnica-EME LIGHT GREY",
    pdfLink: "/downloads/Ficha-Técnica-EME LIGHT GREY.pdf",
  },
  {
    id: "kendo_classic",
    titulo: "kendo classic //",
    imgL: require("../../../assets/images/piedra/kendo_classic.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/piedra/kendo_classic_01.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/kendo_classic.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "piedra / stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/bath/eme-light-grey",
    urlsiguiente: "/bath/kendo-light",
    pdfNombre: "Ficha-Técnica-KENDO CLASSIC",
    pdfLink: "/downloads/Ficha-Técnica-KENDO CLASSIC.pdf",
  },
  {
    id: "kendo_light",
    titulo: "kendo light //",
    imgL: require("../../../assets/images/piedra/kendo_light.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/piedra/kendo_light_01.webp"),
    img2: require("../../../assets/images/piedra/kendo_light_02.webp"),
    imgVid: require("../../../assets/videos/kendo_light.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "cemento / cement",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/bath/kendo-classic",
    urlsiguiente: "/bath/moma-gris",
    pdfNombre: "",
    pdfLink: "/downloads/Ficha-Técnica-KENDO LIGHT.pdf",
  },
  {
    id: "moma_gris",
    titulo: "moma gris //",
    imgL: require("../../../assets/images/cementos/moma_gris.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/cementos/moma_gris_01.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/moma_gris.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "cemento / concrete", ""],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/bath/kendo-light",
    urlsiguiente: "/bath/negro-marquina",
    pdfNombre: "Ficha-Técnica-MomaGris",
    pdfLink: "/downloads/Ficha-Técnica-MomaGris.pdf",
  },
  {
    id: "negro_marquina",
    titulo: "negro marquina //",
    imgL: require("../../../assets/images/marmol/negro_marquina.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/marmol/negro_marquina_01.webp"),
    imgVid: require("../../../assets/videos/negro_marquina.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "cemento / cement",
      "1 único diseño / 1 single design",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/bath/moma-gris",
    urlsiguiente: "/bath/noon-grey",
    pdfNombre: "Ficha-Técnica-NegroMarquina",
    pdfLink: "/downloads/Ficha-Técnica-NegroMarquina.pdf",
  },
  {
    id: "noon_grey",
    titulo: "noon grey //",
    imgL: require("../../../assets/images/piedra/noon_grey.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/piedra/noon_grey_01.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/noon_grey.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "piedra del norte / northern stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/bath/negro-marquina",
    urlsiguiente: "/bath/noon-sand",
    pdfNombre: "Ficha-Técnica-NOON GREY",
    pdfLink: "/downloads/Ficha-Técnica-NOON GREY.pdf",
  },
  {
    id: "noon_sand",
    titulo: "noon sand //",
    imgL: require("../../../assets/images/piedra/noon_sand.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/piedra/noon_sand_1.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/noon_sand.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "piedra del norte / northern stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/bath/noon-grey",
    urlsiguiente: "/bath/paladio",
    pdfNombre: "Ficha-Técnica-NOON SAND",
    pdfLink: "/downloads/Ficha-Técnica-NOON SAND.pdf",
  },

  {
    id: "paladio",
    titulo: "paladio //",
    imgL: require("../../../assets/images/marmol/paladio.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/marmol/paladio_01.webp"),
    img2: require("../../../assets/images/marmol/paladio_02.webp"),
    imgVid: require("../../../assets/videos/paladio_marron_pulido.mp4"),
    desc: [
      "natural s/ r // pulido s/r 1620x3240 mm / 63,7”x127,5”",
      "mármol / marble stone",
      "",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/bath/noon-sand",
    urlsiguiente: "/bath/syrac",
    pdfNombre: "Ficha-Técnica-Paladio",
    pdfLink: "/downloads/Ficha-Técnica-Paladio.pdf",
  },
  {
    id: "syrac",
    titulo: "syrac //",
    imgL: require("../../../assets/images/marmol/syrac.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    espesor2: require("../../../assets/icons/espesores/20mm.png"),
    img1: require("../../../assets/images/marmol/syrac_01.webp"),
    imgVid: require("../../../assets/videos/syrac.mp4"),
    desc: [
      "hond 1600x3200 mm/ 63”x126”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/bath/paladio",
    urlsiguiente: "/bath/allure-anthracite",
    pdfNombre: "Ficha-Técnica-Syrac",
    pdfLink: "/downloads/Ficha-Técnica-Syrac.pdf",
  },
];
