export const Footer = {
  footer: "volver a colecciones //",
  footerImg: require("../../../assets/icons/introduccion/logo.png"),
};
export const PaginasColor = [
  {
    id: "basic_blanco",
    titulo: "basic blanco //",
    imgL: require("../../../assets/images/color/basic_blanco.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    espesor2: require("../../../assets/icons/espesores/20mm.png"),
    img1: require("../../../assets/images/color/basic_blanco_01.webp"),
    imgVid: require("../../../assets/videos/basic_blanco.mp4"),
    desc: [
      "blanco natural mate s/r // pulido s/r 1620x3240 mm / 63,7”x127,5”",
      "color liso / uniform color",
      "",
    ],

    desc2: [
      "blanco natural mate 1600x3200 mm / 63”x126”",
      "color liso / uniform color",
      "",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/pure-super-white",
    urlsiguiente: "/colecciones/basic-negro",
  },
  {
    id: "basic_negro",
    titulo: "basic negro //",
    imgL: require("../../../assets/images/color/basic_negro.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/color/basic_negro_01.webp"),
    imgVid: require("../../../assets/videos/basic_negro.mp4"),
    desc: [
      "negro natural mate s/r 1620x3240 mm / 63,7”x127,5”",
      "color liso / uniform color",
      "",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/basic-blanco",
    urlsiguiente: "/colecciones/era-deep-black",
  },
  {
    id: "era_deep_black",
    titulo: "era deep black //",
    imgL: require("../../../assets/images/color/era_deep_black.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/color/era_deep_black_1.webp"),
    imgVid: require("../../../assets/videos/era_deep_black.mp4"),
    desc: [
      "soft 1620x3240 mm / 63,7”x127,5”",
      "color liso / uniform color",
      "",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/basic-negro",
    urlsiguiente: "/colecciones/era-grey",
  },
  {
    id: "era_grey",
    titulo: "era grey //",
    imgL: require("../../../assets/images/color/era_grey.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/color/basic_blanco_01.webp"),
    imgVid: require("../../../assets/videos/era_grey.mp4"),
    desc: [
      "soft 1620x3240 mm / 63,7”x127,5”",
      "color liso / uniform color",
      "",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/era-deep-black",
    urlsiguiente: "/colecciones/era-infinity-white",
  },
  {
    id: "era_infinity_white",
    titulo: "era infinity white //",
    imgL: require("../../../assets/images/color/era_infinity_white.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/color/era_infinity_white_1.webp"),
    imgVid: require("../../../assets/videos/era_infinity_white.mp4"),
    desc: [
      "soft 1620x3240 mm / 63,7”x127,5”",
      "color liso / uniform color",
      "",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/era-grey",
    urlsiguiente: "/colecciones/era-white",
  },
  {
    id: "era_white",
    titulo: "era white //",
    imgL: require("../../../assets/images/color/era_white.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/color/era_white_01.webp"),
    imgVid: require("../../../assets/videos/era_white.mp4"),
    desc: [
      "soft 1620x3240 mm / 63,7”x127,5”",
      "color liso / uniform color",
      "",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/era-infinity-white",
    urlsiguiente: "/colecciones/pure-black",
  },
  {
    id: "pure_black",
    titulo: "pure black //",
    imgL: require("../../../assets/images/color/pure_black.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/color/pure_black_01.webp"),
    imgVid: require("../../../assets/videos/pure_black.mp4"),
    desc: ["hond 1600x3200 mm/ 63”x126”", "color liso / uniform color", ""],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/era-white",
    urlsiguiente: "/colecciones/pure-super-white",
  },
  {
    id: "pure_super_white",
    titulo: "pure super white //",
    imgL: require("../../../assets/images/color/pure_super_white.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    espesor2: require("../../../assets/icons/espesores/20mm.png"),
    img1: require("../../../assets/images/color/pure_super_white_01.webp"),
    imgVid: require("../../../assets/videos/pure_super_white.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "cemento / cement",
      "1 único diseño / 1 single design",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/colecciones/pure-black",
    urlsiguiente: "/colecciones/basic-blanco",
  },
];
