export const InterGrandeObj = {
  base: require("../../../assets/images/bath/intergrande/XL CONFIGURADOR FONDO OK.webp"),
  //----------------Frontal----------------
  allureFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL ALLURE ANTHRACITE.webp"),
  berenFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL BEREN LIGHT GREY.webp"),
  blancBorghiniFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL BLANC BORGHINI.webp"),
  blancInvisibleFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL BLANC INVISIBLE.webp"),
  brazilFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL BRAZIL SUPER WHITE.webp"),
  calacattaFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL CALACATTA.webp"),
  emeFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL EME LIGHT GREY.webp"),
  kendoCFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL KENDO CLASSIC.webp"),
  kendoLFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL KENDO LIGHT.webp"),
  momaFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL MOMA GRIS.webp"),
  negroFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL NEGRO MARQUINA.webp"),
  noonGFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL NOON GREY.webp"),
  noonSFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL NOON SAND.webp"),
  paladioFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL PALADIO.webp"),
  syracFRONTAL: require("../../../assets/images/bath/intergrande/FRONTAL/FRONTAL SYRAC.webp"),

  //----------------MUEBLE----------------
  antracitaMueble: require("../../../assets/images/bath/intergrande/MUEBLE/CUERPO MUEBLE ANTRACITA.webp"),
  blancoMueble: require("../../../assets/images/bath/intergrande/MUEBLE/CUERPO MUEBLE BLANCO.webp"),
  naturalMueble: require("../../../assets/images/bath/intergrande/MUEBLE/CUERPO MUEBLE NATURAL.webp"),
  //----------------PAVIMENTO----------------
  allurePAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO ALLURE ANTHRACITE.webp"),
  berenPAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO BEREN LIGHT GREY.webp"),
  blancBorghiniPAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO BLANC BORGHINI.webp"),
  blancInvisiblePAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO BLANC INVISIBLE.webp"),
  brazilPAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO BRAZIL SUPER WHITE.webp"),
  calacattaPAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO CALACATTA.webp"),
  emePAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO EME LIGHT GREY.webp"),
  kendoCPAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO KENDO CLASSIC.webp"),
  kendoLPAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO KENDO LIGHT.webp"),
  momaPAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO MOMA GRIS.webp"),
  negroPAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/NEGRO MARQUINA.webp"),
  noonGPAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO NOON GREY.webp"),
  noonSPAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO NOON SAND.webp"),
  paladioPAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO PALADIO.webp"),
  syracPAVIMENTO: require("../../../assets/images/bath/intergrande/PAVIMENTO/PAVIMENTO SYRAC.webp"),
  //----------------PLATOS----------------
  allurePLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO ALLURE ANTHRACITE.webp"),
  berenPLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO BEREN LIGHT GREY.webp"),
  blancBorghiniPLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO BLANC BORGHINI.webp"),
  blancInvisiblePLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO BLANC INVISIBLE.webp"),
  brazilPLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO BRAZIL SUPER WHITE.webp"),
  calacattaPLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO CALACATTA.webp"),
  emePLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO EME LIGHT GREY.webp"),
  kendoCPLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO KENDO CLASSIC.webp"),
  kendoLPLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO KENDO LIGHT.webp"),
  momaPLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO MOMA GRIS.webp"),
  negroPLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO NEGRO MARQUINA.webp"),
  noonGPLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO NOON GREY.webp"),
  noonSPLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO NOON SAND.webp"),
  paladioPLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO PALADIO.webp"),
  syracPLATOS: require("../../../assets/images/bath/intergrande/PLATOS/PLATO SYRAC.webp"),

  //---------------- REVESTIMIENTO----------------
  allureREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO ALLURE ANTHRACITE.webp"),
  berenREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO BEREN LIGHT GREY.webp"),
  blancBorghiniREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO BLANC BORGHINI.webp"),
  blancInvisibleREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO BLANC INVISIBLE.webp"),
  brazilREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO BRAZIL SUPER WHITE.webp"),
  calacattaREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO CALACATTA.webp"),
  emeREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO EME LIGHT GREY.webp"),
  kendoCREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO KENDO CLASSIC.webp"),
  kendoLREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO KENDO LIGHT.webp"),
  momaREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO MOMA GRIS.webp"),
  negroREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO NEGRO MARQUINA.webp"),
  noonGREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO NOON GREY.webp"),
  noonSREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO NOON SAND.webp"),
  paladioREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO PALADIO.webp"),
  syracREVESTIMIENTO: require("../../../assets/images/bath/intergrande/REVESTIMIENTO/REVESTIMIENTO SYRAC.webp"),

  //---------------- XL ENCIMERA----------------
  allureXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA ALLURE ANTHRACITE.webp"),
  berenXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA BEREN LIGHT GREY.webp"),
  blancBorghiniXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA BLANC BORGHINI.webp"),
  blancInvisibleXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA BLANC INVISIBLE.webp"),
  brazilXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA BRAZIL SUPER WHITE.webp"),
  calacattaXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA CALACATTA.webp"),
  emeXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA EME LIGHT GREY.webp"),
  kendoCXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA KENDO CLASSIC.webp"),
  kendoLXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA KENDO LIGHT.webp"),
  momaXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA MOMA GRIS.webp"),
  negroXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA NEGRO MARQUINA.webp"),
  noonGXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA NOON GREY.webp"),
  noonSXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA NOON SAND.webp"),
  paladioXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA PALADIO.webp"),
  syracXL: require("../../../assets/images/bath/intergrande/XL ENCIMERA/XL ENCIMERA SYRAC.webp"),

  //---------------- XL FRONTAL----------------
  allureXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL ALLURE ANTHRACITE.webp"),
  berenXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL BEREN LIGHT GREY.webp"),
  blancBorghiniXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL BLANC BORGHINI.webp"),
  blancInvisibleXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL BLANC INVISIBLE.webp"),
  brazilXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL BRAZIL SUPER WHITE.webp"),
  calacattaXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL CALACATTA.webp"),
  emeXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL EME LIGHT GREY.webp"),
  kendoCXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL KENDO CLASSIC.webp"),
  kendoLXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL KENDO LIGHT.webp"),
  momaXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL MOMA GRIS.webp"),
  negroXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL NEGRO MARQUINA.webp"),
  noonGXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL NOON GREY.webp"),
  noonSXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL NOON SAND.webp"),
  paladioXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL PALADIO.webp"),
  syracXLFRONTAL: require("../../../assets/images/bath/intergrande/XL FRONTAL/XL FRONTAL SYRAC.webp"),

  //---------------- XL FRONTAL MODULO----------------
  allureXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO ALLURE ANTHRACITE.webp"),
  berenXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO BEREN LIGHT GREY.webp"),
  blancBorghiniXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO BLANC BORGHINI.webp"),
  blancInvisibleXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO BLANC INVISIBLE.webp"),
  brazilXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO BRAZIL SUPER WHITE.webp"),
  calacattaXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO CALACATTA.webp"),
  emeXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO EME LIGHT GREY.webp"),
  kendoCXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO KENDO CLASSIC.webp"),
  kendoLXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO KENDO LIGHT.webp"),
  momaXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO MOMA GRIS.webp"),
  negroXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO NEGRO MARQUINA.webp"),
  noonGXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO NOON GREY.webp"),
  noonSXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO NOON SAND.webp"),
  paladioXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO PALADIO.webp"),
  syracXLFRONTALMODULO: require("../../../assets/images/bath/intergrande/XL FRONTAL MODULO/XL FRONTAL MODULO SYRAC.webp"),

  //---------------- XL LATERALES----------------
  allureXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES ALLURE ANTHRACITE.webp"),
  berenXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES BEREN LIGHT GREY.webp"),
  blancBorghiniXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES BLANC BORGHINI.webp"),
  blancInvisibleXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES BLANC INVISIBLE.webp"),
  brazilXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES BRAZIL SUPER WHITE.webp"),
  calacattaXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES CALACATTA.webp"),
  emeXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES EME LIGHT GREY.webp"),
  kendoCXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES KENDO CLASSIC.webp"),
  kendoLXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES KENDO LIGHT.webp"),
  momaXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES MOMA GRIS.webp"),
  negroXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES NEGRO MARQUINA.webp"),
  noonGXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES NOON GREY.webp"),
  noonSXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES NOON SAND.webp"),
  paladioXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES PALADIO.webp"),
  syracXLLATERAL: require("../../../assets/images/bath/intergrande/XL LATERALES/XL LATERALES SYRAC.webp"),
  //---------------- XL LAVABO----------------
  allureXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO ALLURE ANTHRACITE.webp"),
  berenXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO BEREN LIGHT GREY.webp"),
  blancBorghiniXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO BLANC BORGHINI.webp"),
  blancInvisibleXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO BLANC INVISIBLE.webp"),
  brazilXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO BRAZIL SUPER WHITE.webp"),
  calacattaXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO CALACATTA.webp"),
  emeXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO EME LIGHT GREY.webp"),
  kendoCXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO KENDO CLASSIC.webp"),
  kendoLXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO KENDO LIGHT.webp"),
  momaXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO MOMA GRIS.webp"),
  negroXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO NEGRO MARQUINA.webp"),
  noonGXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO NOON GREY.webp"),
  noonSXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO NOON SAND.webp"),
  paladioXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO PALADIO.webp"),
  syracXLLAVABO: require("../../../assets/images/bath/intergrande/XL LAVABO/XL LAVABO SYRAC.webp"),
  //---------------- TEXTOS----------------
  acabadoAllure: "allure anthracite",
  acabadoBeren: "beren light grey",
  acabadoBlancBorghini: "blanc borghini",
  acabadoBlancInvisible: "blanc invisible",
  acabadoBrazil: "brazil super white",
  acabadoCalacatta: "calacatta",
  acabadoEme: "eme light grey",
  acabadoKendoC: "kendo classic",
  acabadoKendoL: "kendo light",
  acabadoMoma: "moma gris",
  acabadoNegroM: "negro marquina",
  acabadoNoonG: "noon grey",
  acabadoNoonS: "noon sand",
  acabadoPaladio: "paladio",
  acabadoSyrac: "syrac",
  acabadoNatural: "madera natural",
  acabadoAntracita: "lacado antracita",
  acabadoBlanco: "lacado blanco",
  acabadoNordik: "madera nordik",
};
