export {
  // ArabescattoEN,
  AtlantisEN,
  BlancArabeEN,
  BlancBorgEN,
  BlancCalaEN,
  BlancCalaGoldEN,
  BlancInvEN,
  BlancStatGoldEN,
  BlancStatEN,
  BrazilSuperEN,
  CalacattaEN,
  CalacattaGoldEN,
  CalacattaPaoEN,
  CorintoEN,
  CuarzoRenoEN,
  EstatuarioEN,
  EstatuarioBKAEN,
  IcebergEN,
  // InvisibleGreyEN,
  LilacEN,
  MelbourneEN,
  NegroMarqEN,
  NeroArdiEN,
  PaladioEN,
  // RosaPersiaEN,
  SaharaNoirEN,
  SaintLaurenEN,
  SyracEN,
  // VolakasEN,
} from "./marmolesConsolidados";
