export const Footer = {
  footer: "volver a colecciones //",
  footerImg: require("../../../assets/icons/introduccion/logo.png"),
};
export const PaginasCemento = [
  {
    id: "blue_stone_gris",
    titulo: "blue stone gris //",
    imgL: require("../../../assets/images/cementos/blue_stone_gris.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/cementos/blue_stone_gris_01.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/blue_stone_gris.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "cemento / concrete", ""],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/vulcano",
    urlsiguiente: "/colecciones/moma-arena",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "moma_arena",
    titulo: "moma arena //",
    imgL: require("../../../assets/images/cementos/moma_arena.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/cementos/moma_arena_01.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/moma_arena.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "cemento / concrete", ""],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/blue-stone-gris",
    urlsiguiente: "/colecciones/moma-gris",
    pdfNombre: "DataTest.pdf",
    pdfLink: "/downloads/test.pdf",
  },
  {
    id: "moma_gris",
    titulo: "moma gris //",
    imgL: require("../../../assets/images/cementos/moma_gris.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/cementos/moma_gris_01.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/moma_gris.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "cemento / concrete", ""],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/moma-arena",
    urlsiguiente: "/colecciones/kron-grey",
    pdfNombre: "null",
    pdfLink: "null",
  },

  {
    id: "kron_grey",
    titulo: "kron grey //",
    imgL: require("../../../assets/images/cementos/kron_grey.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/cementos/kron_grey_01.webp"),
    img2: require("../../../assets/images/cementos/kron_grey_02.webp"),
    imgVid: require("../../../assets/videos/kron_grey.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "cemento / concrete",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/moma-gris",
    urlsiguiente: "/colecciones/titan-antracita",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "titan_antracita",
    titulo: "titan antracita //",
    imgL: require("../../../assets/images/cementos/titan_antracita.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/cementos/titan_antracita_01.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/titan_antracita.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "cemento / concrete", ""],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/kron-grey",
    urlsiguiente: "/colecciones/titan-cemento",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "titan_cemento",
    titulo: "titan cemento //",
    imgL: require("../../../assets/images/cementos/titan_cemento.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/cementos/titan_cemento_01.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/titan_cemento.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "cemento / concrete", ""],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/titan-antracita",
    urlsiguiente: "/colecciones/mood-anthracite",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "mood_anthracite",
    titulo: "mood anthracite //",
    imgL: require("../../../assets/images/cementos/mood_anthracite.webp"),
    img1: require("../../../assets/images/cementos/mood_anthracite_1.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    imgVid: require("../../../assets/videos/mood_anthracite.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "micro cemento / micro concrete",
      "2 diseños / 2 designs",
    ],
    verimg: "",
    vervid: "",
    altL: "imagenL",
    altImg1: "//",
    altImg2: "imagen2",
    altVid: "//",
    urlanterior: "/colecciones/titan-cemento",
    urlsiguiente: "/colecciones/mood-grey",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "mood_grey",
    titulo: "mood grey //",
    imgL: require("../../../assets/images/cementos/mood_grey.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/cementos/mood_grey_01.webp"),
    img2: require("../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../assets/videos/mood_grey.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "micro cemento / micro concrete",
      " ",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/mood-anthracite",
    urlsiguiente: "/colecciones/vulcano",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "vulcano",
    titulo: "vulcano //",
    imgL: require("../../../assets/images/cementos/vulcano.webp"),
    espesor: require("../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../assets/images/cementos/vulcano_01.webp"),
    img2: require("../../../assets/images/cementos/vulcano_02.webp"),
    imgVid: require("../../../assets/videos/moma_gris.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "cemento / cement",
      "1 único diseño / 1 single design",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/colecciones/mood-grey",
    urlsiguiente: "/colecciones/blue-stone-gris",
    pdfNombre: "",
    pdfLink: "",
  },
];
