export const Footer = {
  footer: "volver a colecciones //",
  footerImg: require("../../../../assets/icons/introduccion/logo.png"),
};
export const PaginasMarmol = [
  {
    id: "arabescatto_corchia",
    titulo: "arabescatto corchia //",
    imgL: require("../../../../assets/images/marmol/arabescatto_corchia.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/arabescatto_corchia_01.webp"),
    imgVid: require("../../../../assets/videos/arabescatto_corchia.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "mármol blanco / white marble stone",
      "1 único diseño / 1 single design",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/en/colecciones/volakas",
    urlsiguiente: "/en/colecciones/atlantis",
  },
  {
    id: "atlantis",
    titulo: "atlantis gold //",
    imgL: require("../../../../assets/images/marmol/atlantis.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/atlantis_01.webp"),
    imgVid: require("../../../../assets/videos/atlantis_gold.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "mármol blanco / white marble stone",
      "1 único diseño / 1 single design",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/en/colecciones/arabescatto-corchia",
    urlsiguiente: "/en/colecciones/blanc-arabescato",
  },
  {
    // <----------------------------Falta Video!
    id: "blanc_arabescato",
    titulo: "blanc arabescato //",
    imgL: require("../../../../assets/images/marmol/blanc_arabescato.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/blanc_arabescato_01.webp"),
    imgVid: require("../../../../assets/videos/blanc_arabescato.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/en/colecciones/atlantis",
    urlsiguiente: "/en/colecciones/blanc-borghini",
  },
  {
    id: "blanc_borghini",
    titulo: "blanc borghini //",
    imgL: require("../../../../assets/images/marmol/blanc_borghini.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/blanc_borghini_01.webp"),
    img2: require("../../../../assets/images/marmol/blanc_borghini_02.webp"),
    imgVid: require("../../../../assets/videos/blanc_borghini.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/blanc-arabescato",
    urlsiguiente: "/en/colecciones/blanc-calacatta",
  },
  {
    id: "blanc_calacatta",
    titulo: "blanc calacatta //",
    imgL: require("../../../../assets/images/marmol/blanc_calacatta.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/blanc_calacatta_01.webp"),
    img2: require("../../../../assets/images/marmol/blanc_calacatta_02.webp"),
    imgVid: require("../../../../assets/videos/blanc_calacatta.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/blanc-borghini",
    urlsiguiente: "/en/colecciones/blanc-calacatta-gold",
  },
  {
    id: "blanc_calacatta_gold",
    titulo: "blanc calacatta gold //",
    imgL: require("../../../../assets/images/marmol/blanc_calacatta_gold.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/blanc_calacatta_gold_01.webp"),
    img2: require("../../../../assets/images/marmol/blanc_calacatta_gold_02.webp"),
    imgVid: require("../../../../assets/videos/blanc_calacatta_gold.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/blanc-calacatta",
    urlsiguiente: "/en/colecciones/blanc-invisible",
  },
  {
    id: "blanc_invisible",
    titulo: "blanc invisible //",
    imgL: require("../../../../assets/images/marmol/blanc_invisible.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/blanc_invisible_01.webp"),
    imgVid: require("../../../../assets/videos/blanc_invisible.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/en/colecciones/blanc-calacatta-gold",
    urlsiguiente: "/en/colecciones/blanc-statuario-gold",
  },

  {
    id: "blanc_statuario_gold",
    titulo: "blanc statuario gold //",
    imgL: require("../../../../assets/images/marmol/blanc_statuario_gold.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/blanc_statuario_gold_01.webp"),
    img2: require("../../../../assets/images/marmol/blanc_statuario_gold_02.webp"),
    imgVid: require("../../../../assets/videos/blanc_statuario_gold.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/blanc-invisible",
    urlsiguiente: "/en/colecciones/blanc-statuarietto",
  },

  {
    id: "blanc_statuarietto",
    titulo: "blanc statuarietto //",
    imgL: require("../../../../assets/images/marmol/blanc_statuarietto.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/blanc_statuarietto_01.webp"),
    imgVid: require("../../../../assets/videos/blanc_statuarietto.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/en/colecciones/blanc-statuario-gold",
    urlsiguiente: "/en/colecciones/brazil-super-white",
  },
  {
    id: "brazil_super_white",
    titulo: "brazil super white //",
    imgL: require("../../../../assets/images/marmol/brazil_super_white.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    espesor2: require("../../../../assets/icons/espesores/20mm.png"),
    img1: require("../../../../assets/images/marmol/brazil_super_white_01.webp"),
    img2: require("../../../../assets/images/marmol/brazil_super_white_02.webp"),
    imgVid: require("../../../../assets/videos/brazil_super_white.mp4"),
    desc: [
      "hond 1600x3200 mm/ 63”x126”",
      "mármol / marble",
      "1 único diseño / 1 single design",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/blanc-statuarietto",
    urlsiguiente: "/en/colecciones/calacatta",
  },
  {
    id: "calacatta",
    titulo: "calacatta //",
    imgL: require("../../../../assets/images/marmol/calacatta.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    espesor2: require("../../../../assets/icons/espesores/20mm.png"),
    img1: require("../../../../assets/images/marmol/calacatta_01.webp"),
    img2: require("../../../../assets/images/marmol/calacatta_02.webp"),
    imgVid: require("../../../../assets/videos/calacatta_pulido.mp4"),
    desc: [
      "natural s/r // pulido s/r 1620x3240 mm / 63,7”x127,5”",
      "mármol / marble stone",
      "",
    ],

    desc2: ["natural s/r 1600x3200 mm/ 63”x126”", "mármol / marble stone", ""],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/brazil-super-white",
    urlsiguiente: "/en/colecciones/calacatta-gold",
  },
  {
    id: "calacatta_gold",
    titulo: "calacatta gold //",
    imgL: require("../../../../assets/images/marmol/calacatta_gold.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/calacatta_gold_01.webp"),
    img2: require("../../../../assets/images/marmol/calacatta_gold_02.webp"),
    imgVid: require("../../../../assets/videos/calacatta_gold.mp4"),
    desc: [
      "hond 1600x3200 mm/ 63”x126”",
      "piedra / stone",
      "1 único diseño / 1 single design",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/calacatta",
    urlsiguiente: "/en/colecciones/calacatta-paonazzo",
  },
  {
    // <----------------------------Falta Video!
    id: "calacatta_paonazzo",
    titulo: "calacatta paonazzo //",
    imgL: require("../../../../assets/images/marmol/calacatta_paonazzo.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    espesor2: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/calacatta_paonazzo_01.webp"),
    img2: require("../../../../assets/images/marmol/calacatta_paonazzo_02.webp"),
    imgVid: require("../../../../assets/videos/calacatta_paonazzo.mp4"),
    desc: [
      "hond 1600x3200 mm/ 63”x126”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/calacatta-gold",
    urlsiguiente: "/en/colecciones/corinto",
  },

  {
    id: "corinto",
    titulo: "corinto //",
    imgL: require("../../../../assets/images/marmol/corinto.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/corinto_01.webp"),
    img2: require("../../../../assets/images/marmol/corinto_02.webp"),
    imgVid: require("../../../../assets/videos/corinto.mp4"),
    desc: [
      "natural s/r 1620x3240 mm / 63,7”x127,5”",
      "mármol / marble stone",
      "",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/calacatta-paonazzo",
    urlsiguiente: "/en/colecciones/cuarzo-reno",
  },

  {
    id: "cuarzo_reno",
    titulo: "cuarzo reno //",
    imgL: require("../../../../assets/images/marmol/cuarzo_reno.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/cuarzo_reno_01.webp"),
    img2: require("../../../../assets/images/marmol/cuarzo_reno_02.webp"),
    imgVid: require("../../../../assets/videos/cuarzo_reno.mp4"),
    desc: ["pulido 1620x3240 mm / 63,7”x127,5”", "mármol / marble stone", " "],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/corinto",
    urlsiguiente: "/en/colecciones/estatuario",
  },
  {
    id: "estatuario",
    titulo: "estatuario //",
    imgL: require("../../../../assets/images/marmol/estatuario.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    espesor2: require("../../../../assets/icons/espesores/20mm.png"),
    img1: require("../../../../assets/images/marmol/estatuario_01.webp"),
    img2: require("../../../../assets/images/marmol/estatuario_02.webp"),
    imgVid: require("../../../../assets/videos/estatuario.mp4"),
    desc: [
      "hond // polished 1600x3200 mm/ 63”x126”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/cuarzo-reno",
    urlsiguiente: "/en/colecciones/estatuario-bk-a",
  },

  {
    id: "estatuario_bk-a",
    titulo: "estatuario bk-a //",
    imgL: require("../../../../assets/images/marmol/estatuario_bk-a.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/estatuario_bk-a_01.webp"),
    imgVid: require("../../../../assets/videos/estatuario_bk_a_pulido.mp4"),
    desc: [
      "natural s/r // pulido s/r 1620x3240 mm / 63,7”x127,5”",
      "mármol / marble stone",
      " ",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/en/colecciones/estatuario",
    urlsiguiente: "/en/colecciones/iceberg",
  },
  {
    id: "iceberg",
    titulo: "iceberg //",
    imgL: require("../../../../assets/images/marmol/iceberg.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/iceberg_01.webp"),
    imgVid: require("../../../../assets/videos/iceberg.mp4"),
    desc: [
      "natural s/r // pulido s/r 1620x3240 mm / 63,7”x127,5”",
      "mármol / marble stone",
      " ",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/en/colecciones/estatuario-bk-a",
    urlsiguiente: "/en/colecciones/invisible-grey",
  },

  {
    id: "invisible_grey",
    titulo: "invisible grey //",
    imgL: require("../../../../assets/images/marmol/invisible_grey.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/invisible_grey_01.webp"),
    imgVid: require("../../../../assets/videos/invisible_grey.mp4"),
    desc: [
      "hond 1600x3200 mm/ 63”x126”",
      "mármol / marble",
      "1 único diseño / 1 single design",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/en/colecciones/iceberg",
    urlsiguiente: "/en/colecciones/lilac",
  },

  {
    id: "lilac",
    titulo: "lilac //",
    imgL: require("../../../../assets/images/marmol/lilac.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/lilac_01.webp"),
    img2: require("../../../../assets/images/marmol/lilac_02.webp"),
    imgVid: require("../../../../assets/videos/lilac.mp4"),
    desc: [
      "hond 1600x3200 mm/ 63”x126”",
      "mármol de calcita blanca / white calcite marble",
      "1 único diseño / 1 single design",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/lilac",
    urlsiguiente: "/en/colecciones/negro-marquina",
  },

  {
    id: "negro_marquina",
    titulo: "negro marquina //",
    imgL: require("../../../../assets/images/marmol/negro_marquina.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/negro_marquina_01.webp"),
    imgVid: require("../../../../assets/videos/negro_marquina.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "cemento / cement",
      "1 único diseño / 1 single design",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/en/colecciones/lilac",
    urlsiguiente: "/en/colecciones/nero-ardi",
  },

  {
    id: "nero_ardi",
    titulo: "nero ardi //",
    imgL: require("../../../../assets/images/marmol/nero_ardi.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/nero_ardi_1.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/nero_ardi.mp4"),
    desc: [
      "natural s/r 1620x3240 mm / 63,7”x127,5”",
      "mármol / marble stone",
      "",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/negro-marquina",
    urlsiguiente: "/en/colecciones/paladio",
  },

  {
    id: "paladio",
    titulo: "paladio //",
    imgL: require("../../../../assets/images/marmol/paladio.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/paladio_01.webp"),
    img2: require("../../../../assets/images/marmol/paladio_02.webp"),
    imgVid: require("../../../../assets/videos/paladio_marron_pulido.mp4"),
    desc: [
      "natural s/ r // pulido s/r 1620x3240 mm / 63,7”x127,5”",
      "mármol / marble stone",
      "",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/nero-ardi",
    urlsiguiente: "/en/colecciones/rosa-persia",
  },
  {
    id: "rosa_persia",
    titulo: "rosa persia //",
    imgL: require("../../../../assets/images/marmol/rosa_persia.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/rosa_persia_01.webp"),
    img2: require("../../../../assets/images/marmol/rosa_persia_02.webp"),
    imgVid: require("../../../../assets/videos/rosa_persia.mp4"),
    desc: [
      "hond 1600x3200 mm/ 63”x126”",
      "mármol / marble",
      "1 único diseño / 1 single design",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/paladio",
    urlsiguiente: "/en/colecciones/syrac",
  },
  {
    id: "syrac",
    titulo: "syrac //",
    imgL: require("../../../../assets/images/marmol/syrac.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    espesor2: require("../../../../assets/icons/espesores/20mm.png"),
    img1: require("../../../../assets/images/marmol/syrac_01.webp"),
    imgVid: require("../../../../assets/videos/syrac.mp4"),
    desc: [
      "hond 1600x3200 mm/ 63”x126”",
      "mármol blanco / white marble stone",
      "2 diseños / 2 designs",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/en/colecciones/rosa-persia",
    urlsiguiente: "/en/colecciones/volakas",
  },
  {
    id: "volakas",
    titulo: "volakas //",
    imgL: require("../../../../assets/images/marmol/volakas.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/marmol/volakas_01.webp"),
    imgVid: require("../../../../assets/videos/volakas.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "mármol / marble",
      "1 único diseño / 1 single design",
    ],
    desc2: "",
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/en/colecciones/syrac",
    urlsiguiente: "/en/colecciones/arabescatto-corchia",
  },
];
