export {
  ArabescattoEN,
  AtlantisEN,
  BlancArabeEN,
  BlancBorgEN,
  BlancCalaEN,
  BlancCalaGoldEN,
  BlancInvEN,
  BlancStatGoldEN,
  BlancStatEN,
  BrazilSuperEN,
  CalacattaEN,
  CalacattaGoldEN,
  CalacattaPaoEN,
  CorintoEN,
  CuarzoRenoEN,
  EstatuarioEN,
  EstatuarioBKAEN,
  IcebergEN,
  InvisibleGreyEN,
  LilacEN,
  NegroMarqEN,
  NeroArdiEN,
  PaladioEN,
  RosaPersiaEN,
  SyracEN,
  VolakasEN,
} from "./marmolesConsolidados.js";
