export const Footer = {
  footer: "volver a colecciones //",
  footerImg: require("../../../../assets/icons/introduccion/logo.png"),
};
export const PaginasPiedra = [
  {
    id: "allure_anthracite",
    titulo: "allure anthracite //",
    imgL: require("../../../../assets/images/piedra/allure_anthracite.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/allure_anthracite_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/allure_anthracite.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "piedra veteada / marble stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/wega-black",
    urlsiguiente: "/en/colecciones/allure-light-grey",
  },
  {
    id: "allure_light_grey",
    titulo: "allure light grey //",
    imgL: require("../../../../assets/images/piedra/allure_light_grey.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/allure_light_grey_1.webp"),
    imgVid: require("../../../../assets/videos/allure_light_grey.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "piedra veteada / marble stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/allure-anthracite",
    urlsiguiente: "/en/colecciones/amsterdam-grey",
  },
  {
    id: "amsterdam_grey",
    titulo: "amsterdam grey //",
    imgL: require("../../../../assets/images/piedra/amsterdam_grey.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/amsterdam_grey_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/distrito_aluminio.mp4"),
    desc: [
      "natural 1600x3200 mm/ 63”x126”",
      "piedra natural / natural stone",
      "1 único diseño / 1 single design",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/allure-light-grey",
    urlsiguiente: "/en/colecciones/basalt-grey",
  },
  {
    id: "basalt_grey",
    titulo: "basalt grey //",
    imgL: require("../../../../assets/images/piedra/basalt_grey.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/basalt_grey_01.webp"),
    img2: require("../../../../assets/images/piedra/basalt_grey_02.webp"),
    imgVid: require("../../../../assets/videos/basalt_grey.mp4"),
    desc: ["silk 1600x3200 mm/ 63”x126”", "cemento / cement", "piedra / stone"],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/amsterdam-grey",
    urlsiguiente: "/en/colecciones/basaltina-beige",
  },
  {
    id: "basaltina_beige",
    titulo: "basaltina beige //",
    imgL: require("../../../../assets/images/piedra/basaltina_beige.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/basaltina_beige_1.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/basaltina_beige.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "piedra / stone", " "],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/basalt-grey",
    urlsiguiente: "/en/colecciones/bateig-blue",
  },
  {
    id: "bateig_blue",
    titulo: "bateig blue //",
    imgL: require("../../../../assets/images/piedra/bateig_blue.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/bateig_blue_01.webp"),
    img2: require("../../../../assets/images/piedra/bateig_blue_02.webp"),
    imgVid: require("../../../../assets/videos/distrito_aluminio.mp4"),
    desc: [
      "natural 1600x3200 mm/ 63”x126”",
      "piedra caliza / limestone",
      "1 único diseño / 1 single design",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/basaltina-beige",
    urlsiguiente: "/en/colecciones/bera-ice",
  },
  {
    id: "bera_ice",
    titulo: "bera ice //",
    imgL: require("../../../../assets/images/piedra/bera_ice.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/bera_ice_1.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/bera_ice.mp4"),
    desc: [
      "soft 1620x3240 mm/ 63”x127”",
      "caliza lusitana & catalana / lusitan & catalan limestone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/bateig-blue",
    urlsiguiente: "/en/colecciones/beren-black",
  },
  {
    id: "beren_black",
    titulo: "beren black //",
    imgL: require("../../../../assets/images/piedra/beren_black.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/beren_black_1.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/beren_black.mp4"),
    desc: [
      "soft 1620x3240 mm/ 63”x127”",
      "caliza lusitana & catalana / lusitan & catalan limestone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/bera-ice",
    urlsiguiente: "/en/colecciones/beren-light-grey",
  },
  {
    id: "beren_light_grey",
    titulo: "beren light grey //",
    imgL: require("../../../../assets/images/piedra/beren_light_grey.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/beren_light_grey_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/beren_light_grey.mp4"),
    desc: [
      "soft 1620x3240 mm/ 63”x127”",
      "caliza lusitana & catalana / lusitan & catalan limestone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/beren-black",
    urlsiguiente: "/en/colecciones/camargue-arena",
  },
  {
    id: "camargue_arena",
    titulo: "camargue arena //",
    imgL: require("../../../../assets/images/piedra/camargue_arena.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/camargue_arena_01.webp"),
    img2: require("../../../../assets/images/piedra/camargue_arena_02.webp"),
    imgVid: require("../../../../assets/videos/camargue_arena.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "piedra / stone", " "],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/beren-light-grey",
    urlsiguiente: "/en/colecciones/camargue-blanco",
  },
  {
    id: "camargue_blanco",
    titulo: "camargue blanco //",
    imgL: require("../../../../assets/images/piedra/camargue_blanco.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/camargue_blanco_1.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/camargue_blanco.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "piedra / stone", " "],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/camargue-arena",
    urlsiguiente: "/en/colecciones/edra-grey",
  },
  {
    id: "edra_grey",
    titulo: "edra grey //",
    imgL: require("../../../../assets/images/piedra/edra_grey.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/edra_grey_1.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/edra_grey.mp4"),
    desc: [
      "soft 1620x3240 mm/ 63”x127”",
      "piedra caliza / limestone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/camargue-blanco",
    urlsiguiente: "/en/colecciones/edra-light",
  },
  {
    id: "edra_light",
    titulo: "edra light //",
    imgL: require("../../../../assets/images/piedra/edra_light.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/edra_light_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/edra_light.mp4"),
    desc: [
      "soft 1620x3240 mm/ 63”x127”",
      "piedra caliza / limestone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/edra-grey",
    urlsiguiente: "/en/colecciones/edra-sand",
  },
  {
    id: "edra_sand",
    titulo: "edra sand //",
    imgL: require("../../../../assets/images/piedra/edra_sand.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/edra_sand_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/edra_sand.mp4"),
    desc: [
      "soft 1620x3240 mm/ 63”x127”",
      "piedra caliza / limestone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/edra-light",
    urlsiguiente: "/en/colecciones/eme-light-grey",
  },
  {
    id: "eme_light_grey",
    titulo: "eme light grey //",
    imgL: require("../../../../assets/images/piedra/eme_light_grey.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/eme_light_grey_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/eme_light_grey.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "piedra mediterránea / mediterranean stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/edra-sand",
    urlsiguiente: "/en/colecciones/eme-grey",
  },
  {
    id: "eme_grey",
    titulo: "eme grey //",
    imgL: require("../../../../assets/images/piedra/eme_grey.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/eme_grey_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/eme_grey.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "piedra mediterránea / mediterranean stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/eme-light-grey",
    urlsiguiente: "/en/colecciones/kendo-classic",
  },
  {
    id: "kendo_classic",
    titulo: "kendo classic //",
    imgL: require("../../../../assets/images/piedra/kendo_classic.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/kendo_classic_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/kendo_classic.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "piedra / stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/eme-grey",
    urlsiguiente: "/en/colecciones/kendo-light",
  },
  {
    id: "kendo_light",
    titulo: "kendo light //",
    imgL: require("../../../../assets/images/piedra/kendo_light.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/kendo_light_01.webp"),
    img2: require("../../../../assets/images/piedra/kendo_light_02.webp"),
    imgVid: require("../../../../assets/videos/kendo_light.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "cemento / cement",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/kendo-classic",
    urlsiguiente: "/en/colecciones/noon-grey",
  },
  {
    id: "noon_grey",
    titulo: "noon grey //",
    imgL: require("../../../../assets/images/piedra/noon_grey.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/noon_grey_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/noon_grey.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "piedra del norte / northern stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/kendo-light",
    urlsiguiente: "/en/colecciones/noon-sand",
  },
  {
    id: "noon_sand",
    titulo: "noon sand //",
    imgL: require("../../../../assets/images/piedra/noon_sand.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/noon_sand_1.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/noon_sand.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "piedra del norte / northern stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/noon-grey",
    urlsiguiente: "/en/colecciones/porfido-brown",
  },
  {
    id: "porfido_brown",
    titulo: "pórfido brown //",
    imgL: require("../../../../assets/images/piedra/porfido_brown.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/porfido_brown_01.webp"),
    img2: require("../../../../assets/images/piedra/porfido_brown_02.webp"),
    imgVid: require("../../../../assets/videos/distrito_aluminio.mp4"),
    desc: ["mate 1600x3200 mm/ 63”x126”", "piedra / stone", ""],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/noon-sand",
    urlsiguiente: "/en/colecciones/porfido-sand",
  },
  {
    id: "porfido_sand",
    titulo: "pórfido sand //",
    imgL: require("../../../../assets/images/piedra/porfido_sand.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/porfido_sand_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/porfido_sand.mp4"),
    desc: ["mate 1600x3200 mm/ 63”x126”", "piedra / stone", ""],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/porfido-brown",
    urlsiguiente: "/en/colecciones/wega-black",
  },
  {
    id: "wega_black",
    titulo: "wega black //",
    imgL: require("../../../../assets/images/piedra/wega_black.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/piedra/wega_black_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/wega_black.mp4"),
    desc: [
      "soft textured 1620x3240mm / 63”x127”",
      "piedra volcánica / volcanic stone",
      "2 diseños / 2 designs",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/porfido-sand",
    urlsiguiente: "/en/colecciones/allure-anthracite",
  },
];
