export const acabadoObj = {
  id: "acabados",
  headLine: "Acabados //",
  description:
    "Acabados que reproducen la piedra natural, tecnología 3d·fit® que otorga textura en corcondancia con la gráfica, alto brillo que aporta profundidad y elegancia, acabado natural un efecto más fiel al material original o superficies de acabado sedoso mate, altamente resistentes.",
  description2: "Click para ver los diferentes acabados",
  description3:
    "Soft / Soft textured / Pulido / Natural / Natural S/R / Pulido S/R / Mate / Mate S/R / Silk / Hond",
  img_soft: require("../../assets/images/acabado_soft.webp"),
  img_soft_tx: require("../../assets/images/acabado_soft_textured.webp"),
  img_pulido: require("../../assets/images/acabado_pulido.webp"),
  img_natural: require("../../assets/images/acabado_natural.webp"),
  img_natural_sr: require("../../assets/images/acabado_natural_sr.webp"),
  img_pulido_sr: require("../../assets/images/acabado_pulido_sr.webp"),
  img_mate: require("../../assets/images/acabado_mate.webp"),
  img_mate_sr: require("../../assets/images/acabado_mate_sr.webp"),
  img_silk: require("../../assets/images/acabado_silk.webp"),
  img_hond: require("../../assets/images/acabado_hond.webp"),
  carac_soft: "Soft ",
  carac_soft_tx: "Soft textured ",
  carac_pulido: "Pulido ",
  carac_natural: "Natural ",
  carac_natural_sr: "Natural S/R ",
  carac_pulido_sr: "Pulido S/R ",
  carac_mate: "Mate ",
  carac_mate_sr: "Mate S/R ",
  carac_silk: "Silk ",
  carac_hond: "Hond ",
  alt: "imagen",
};
