/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function Modelo(props) {
  const { nodes, materials } = useGLTF("./modelos_rotador/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1, 4]}>
        <PerspectiveCamera
          makeDefault={false}
          far={20}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.XL_Bath_Lavabo_1_con_grifo_50.geometry}
        material={nodes.XL_Bath_Lavabo_1_con_grifo_50.material}
      />
      <directionalLight
        intensity={1}
        decay={2}
        color='#fcfcfc'
        position={[5, 10, 7.5]}
      />
    </group>
  );
}

useGLTF.preload("./modelos_rotador/scene.gltf");
