export const Colec_Header = {
  id: "header",
  headLine: " Nuestras Colecciones // ",
  subtitle: [
    "cemento y microcemento",
    "color uniformes",
    "mármol",
    "madera",
    "metal",
    "piedra",
  ],
  footer: "volver a inicio //",
  footerImg: require("../../../assets/icons/introduccion/logo.png"),
};

export const Colec_Cemento = [
  {
    id: "blue_stone_gris",
    img: require("../../../assets/images/colecciones/blue_stone_gris.webp"),
    desc: ["blue stone gris //", "1620x3240mm", "12mm"],
    alt: "mini00",
    url: "blue-stone-gris",
  },
  {
    id: "kron_grey",
    img: require("../../../assets/images/colecciones/kron_grey.webp"),
    desc: ["kron grey //", "1620x3240mm", "12mm"],
    alt: "mini01",
    url: "kron-grey",
  },
  {
    id: "moma_arena",
    img: require("../../../assets/images/colecciones/moma_arena.webp"),
    desc: ["moma arena //", "1620x3240mm", "12mm"],
    alt: "mini02",
    url: "moma-arena",
  },
  {
    id: "moma_gris",
    img: require("../../../assets/images/colecciones/moma_gris.webp"),
    desc: ["moma gris //", "1620x3240mm", "12mm"],
    alt: "mini03",
    url: "moma-gris",
  },
  {
    id: "mood_anthracite",
    img: require("../../../assets/images/colecciones/mood_anthracite.webp"),
    desc: ["mood anthracite //", "1620x3240mm", "12mm"],
    alt: "mini04",
    url: "mood-anthracite",
  },

  {
    id: "mood_grey",
    img: require("../../../assets/images/colecciones/mood_grey.webp"),
    desc: ["mood grey //", "1620x3240mm", "12mm"],
    alt: "mini05",
    url: "mood-grey",
  },

  {
    id: "titan_antracita",
    img: require("../../../assets/images/colecciones/titan_antracita.webp"),
    desc: ["titan antracita //", "1620x3240mm", "12mm"],
    alt: "mini06",
    url: "titan-antracita",
  },
  {
    id: "titan_cemento",
    img: require("../../../assets/images/colecciones/titan_cemento.webp"),
    desc: ["titan cemento //", "1620x3240mm", "12mm"],
    alt: "mini07",
    url: "titan-cemento",
  },

  {
    id: "vulcano",
    img: require("../../../assets/images/colecciones/vulcano.webp"),
    desc: ["vulcano //", "1600x3200mm", "12mm"],
    alt: "mini08",
    url: "vulcano",
  },
];

export const Colec_Color = [
  {
    id: "basic_blanco",
    img: require("../../../assets/images/colecciones/basic_blanco.webp"),
    desc: ["basic blanco //", "1620x3240mm", "12mm // 20mm"],
    alt: "mini00",
    url: "basic-blanco",
  },
  {
    id: "basic_negro",
    img: require("../../../assets/images/colecciones/basic_negro.webp"),
    desc: ["basic negro //", "1620x3240mm", "12mm"],
    alt: "mini01",
    url: "basic-negro",
  },
  {
    id: "era_deep_black",
    img: require("../../../assets/images/colecciones/era_deep_black.webp"),
    desc: ["era deep black //", "1620x3240mm", "12mm"],
    alt: "mini02",
    url: "era-deep-black",
  },
  {
    id: "era_grey",
    img: require("../../../assets/images/colecciones/era_grey.webp"),
    desc: ["era grey //", "1620x3240mm", "12mm"],
    alt: "mini03",
    url: "era-grey",
  },
  {
    id: "era_infinity_white",
    img: require("../../../assets/images/colecciones/era_infinity_white.webp"),
    desc: ["era infinity white //", "1620x3240mm", "12mm"],
    alt: "mini04",
    url: "era-infinity-white",
  },
  {
    id: "era_white",
    img: require("../../../assets/images/colecciones/era_white.webp"),
    desc: ["era white //", "1620x3240mm", "12mm"],
    alt: "mini05",
    url: "era-white",
  },
  {
    id: "pure_black",
    img: require("../../../assets/images/colecciones/pure_black.webp"),
    desc: ["pure black //", "1600x3200mm", "12mm"],
    alt: "mini06",
    url: "pure-black",
  },
  {
    id: "pure_super_white",
    img: require("../../../assets/images/colecciones/pure_super_white.webp"),
    desc: ["pure super white //", "1600x3200mm", "12mm // 20mm"],
    alt: "mini07",
    url: "pure-super-white",
  },
];

export const Colec_Marmol = [
  {
    id: "arabescatto_corchia",
    img: require("../../../assets/images/colecciones/arabescatto_corchia.webp"),
    desc: ["arabescatto corchia //", "1600x3200mm", "12mm"],
    alt: "mini00",
    url: "arabescatto-corchia",
  },
  {
    id: "atlantis",
    img: require("../../../assets/images/colecciones/atlantis.webp"),
    desc: ["atlantis gold //", "1600x3200mm", "12mm"],
    alt: "mini01",
    url: "atlantis",
  },
  {
    id: "blanc_arabescato",
    img: require("../../../assets/images/colecciones/blanc_arabescato.webp"),
    desc: ["blanc arabescato //", "1620x3240mm", "12mm"],
    alt: "mini02",
    url: "blanc-arabescato",
  },
  {
    id: "blanc_borghini",
    img: require("../../../assets/images/colecciones/blanc_borghini.webp"),
    desc: ["blanc borghini //", "1620x3240mm", "12mm"],
    alt: "mini03",
    url: "blanc-borghini",
  },
  {
    id: "blanc_calacatta",
    img: require("../../../assets/images/colecciones/blanc_calacatta.webp"),
    desc: ["blanc calacatta //", "1620x3240mm", "12mm"],
    alt: "mini04",
    url: "blanc-calacatta",
  },
  {
    id: "blanc_calacatta_gold",
    img: require("../../../assets/images/colecciones/blanc_calacatta_gold.webp"),
    desc: ["blanc calacatta gold //", "1620x3240mm", "12mm"],
    alt: "mini05",
    url: "blanc-calacatta-gold",
  },
  {
    id: "blanc_invisible",
    img: require("../../../assets/images/colecciones/blanc_invisible.webp"),
    desc: ["blanc invisible //", "1620x3240mm", "12mm"],
    alt: "mini06",
    url: "blanc-invisible",
  },
  {
    id: "blanc_statuario_gold",
    img: require("../../../assets/images/colecciones/blanc_statuario_gold.webp"),
    desc: ["blanc statuario gold //", "1620x3240mm", "12mm"],
    alt: "mini07",
    url: "blanc-statuario-gold",
  },
  {
    id: "blanc_statuarietto",
    img: require("../../../assets/images/colecciones/blanc_statuarietto.webp"),
    desc: ["blanc statuarietto //", "1620x3240mm", "12mm"],
    alt: "mini08",
    url: "blanc-statuarietto",
  },
  {
    id: "brazil_super_white",
    img: require("../../../assets/images/colecciones/brazil_super_white.webp"),
    desc: ["brazil super white //", "1600x3200mm", "12mm // 20mm"],
    alt: "mini09",
    url: "brazil-super-white",
  },
  {
    id: "calacatta",
    img: require("../../../assets/images/colecciones/calacatta.webp"),
    desc: ["calacatta //", "1620x3240mm", "12mm // 20mm"],
    alt: "mini10",
    url: "calacatta",
  },
  {
    id: "calacatta_gold",
    img: require("../../../assets/images/colecciones/calacatta_gold.webp"),
    desc: ["calacatta gold //", "1600x3200mm", "12mm"],
    alt: "mini11",
    url: "calacatta-gold",
  },
  {
    id: "calacatta_paonazzo",
    img: require("../../../assets/images/colecciones/calacatta_paonazzo.webp"),
    desc: ["calacatta paonazzo //", "1600x3200mm", "12mm"],
    alt: "mini11",
    url: "calacatta-paonazzo",
  },
  {
    id: "corinto",
    img: require("../../../assets/images/colecciones/corinto.webp"),
    desc: ["corinto //", "1620x3240mm", "12mm"],
    alt: "mini13",
    url: "corinto",
  },
  {
    id: "cuarzo_reno",
    img: require("../../../assets/images/colecciones/cuarzo_reno.webp"),
    desc: ["cuarzo reno //", "1620x3240mm", "12mm"],
    alt: "mini14",
    url: "cuarzo-reno",
  },
  {
    id: "estatuario",
    img: require("../../../assets/images/colecciones/estatuario.webp"),
    desc: ["estatuario //", "1620x3240mm", "12mm // 20mm"],
    alt: "mini15",
    url: "estatuario",
  },
  {
    id: "estatuario_bk-a",
    img: require("../../../assets/images/colecciones/estatuario_bk-a.webp"),
    desc: ["estatuario bk-a //", "1620x3240mm", "12mm"],
    alt: "mini16",
    url: "estatuario-bk-a",
  },
  {
    id: "iceberg",
    img: require("../../../assets/images/colecciones/iceberg.webp"),
    desc: ["iceberg //", "1620x3240mm", "12mm"],
    alt: "mini17",
    url: "iceberg",
  },
  {
    id: "invisible_grey",
    img: require("../../../assets/images/colecciones/invisible_grey.webp"),
    desc: ["invisible grey //", "1600x3200mm", "12mm"],
    alt: "mini18",
    url: "invisible-grey",
  },
  {
    id: "lilac",
    img: require("../../../assets/images/colecciones/lilac.webp"),
    desc: ["lilac //", "1600x3200mm", "12mm"],
    alt: "mini19",
    url: "lilac",
  },
  {
    id: "negro_marquina",
    img: require("../../../assets/images/colecciones/negro_marquina.webp"),
    desc: ["negro marquina //", "1600x3200mm", "12mm"],
    alt: "mini20",
    url: "negro-marquina",
  },
  {
    id: "nero_ardi",
    img: require("../../../assets/images/colecciones/nero_ardi.webp"),
    desc: ["nero ardi//", "1620x3240mm", "12mm"],
    alt: "mini21",
    url: "nero-ardi",
  },
  {
    id: "paladio",
    img: require("../../../assets/images/colecciones/paladio.webp"),
    desc: ["paladio //", "1620x3240mm", "12mm"],
    alt: "mini22",
    url: "paladio",
  },
  {
    id: "rosa_persia",
    img: require("../../../assets/images/colecciones/rosa_persia.webp"),
    desc: ["rosa persia //", "1600x3200mm", "12mm"],
    alt: "mini23",
    url: "rosa-persia",
  },
  {
    id: "syrac",
    img: require("../../../assets/images/colecciones/syrac.webp"),
    desc: ["syrac //", "1600x3200mm", "12mm // 20mm"],
    alt: "mini24",
    url: "syrac",
  },
  {
    id: "volakas",
    img: require("../../../assets/images/colecciones/volakas.webp"),
    desc: ["volakas //", "1600x3200mm", "12mm"],
    alt: "mini25",
    url: "volakas",
  },
];

export const Colec_Madera = [
  {
    id: "canada",
    img: require("../../../assets/images/colecciones/canada.webp"),
    desc: ["canadá //", "1600x3200mm", "12mm"],
    alt: "mini00",
    url: "canada",
  },
  {
    id: "irati_abeto",
    img: require("../../../assets/images/colecciones/irati_abeto.webp"),
    desc: ["irati abeto //", "1620x3240mm", "12mm"],
    alt: "mini01",
    url: "irati-abeto",
  },
];
export const Colec_Metal = [
  {
    id: "distrito_aluminio",
    img: require("../../../assets/images/colecciones/distrito_aluminio.webp"),
    desc: ["distrito aluminio //", "1620x3240mm", "12mm"],
    alt: "mini00",
    url: "distrito-aluminio",
  },
  {
    id: "distrito_marfil",
    img: require("../../../assets/images/colecciones/distrito_marfil.webp"),
    desc: ["distrito marfil //", "1620x3240mm", "12mm"],
    alt: "mini01",
    url: "distrito-marfil",
  },
  {
    id: "lava_iron",
    img: require("../../../assets/images/colecciones/lava_iron.webp"),
    desc: ["lava iron //", "1620x3240mm", "12mm"],
    alt: "mini02",
    url: "lava-iron",
  },
];

export const Colec_Piedra = [
  {
    id: "allure_anthracite",
    img: require("../../../assets/images/colecciones/allure_anthracite.webp"),
    desc: ["allure anthracite //", "1620x3240mm", "12mm"],
    alt: "mini00",
    url: "allure-anthracite",
  },
  {
    id: "allure_light_grey",
    img: require("../../../assets/images/colecciones/allure_light_grey.webp"),
    desc: ["allure light grey //", "1620x3240mm", "12mm"],
    alt: "mini01",
    url: "allure-light-grey",
  },
  {
    id: "amsterdam_grey",
    img: require("../../../assets/images/colecciones/amsterdam_grey.webp"),
    desc: ["amsterdam grey //", "1600x3200mm", "12mm"],
    alt: "mini02",
    url: "amsterdam-grey",
  },
  {
    id: "basalt_grey",
    img: require("../../../assets/images/colecciones/basalt_grey.webp"),
    desc: ["basalt grey //", "1600x3200mm", "12mm"],
    alt: "mini03",
    url: "basalt-grey",
  },
  {
    id: "basaltina_beige",
    img: require("../../../assets/images/colecciones/basaltina_beige.webp"),
    desc: ["basaltina beige //", "1620x3240mm", "12mm"],
    alt: "mini04",
    url: "basaltina-beige",
  },
  {
    id: "bateig_blue",
    img: require("../../../assets/images/colecciones/bateig_blue.webp"),
    desc: ["bateig blue //", "1600x3200mm", "12mm"],
    alt: "mini05",
    url: "bateig-blue",
  },
  {
    id: "bera_ice",
    img: require("../../../assets/images/colecciones/bera_ice.webp"),
    desc: ["bera ice //", "1620x3240mm", "12mm"],
    alt: "mini06",
    url: "bera-ice",
  },
  {
    id: "beren_black",
    img: require("../../../assets/images/colecciones/beren_black.webp"),
    desc: ["beren black //", "1620x3240mm", "12mm"],
    alt: "mini07",
    url: "beren-black",
  },
  {
    id: "beren_light_grey",
    img: require("../../../assets/images/colecciones/beren_light_grey.webp"),
    desc: ["beren light grey //", "1620x3240mm", "12mm"],
    alt: "mini08",
    url: "beren-light-grey",
  },
  {
    id: "camargue_arena",
    img: require("../../../assets/images/colecciones/camargue_arena.webp"),
    desc: ["camargue arena //", "1620x3240mm", "12mm"],
    alt: "mini09",
    url: "camargue-arena",
  },
  {
    id: "camargue_blanco",
    img: require("../../../assets/images/colecciones/camargue_blanco.webp"),
    desc: ["camargue blanco //", "1620x3240mm", "12mm"],
    alt: "mini10",
    url: "camargue-blanco",
  },
  {
    id: "edra_grey",
    img: require("../../../assets/images/colecciones/edra_grey.webp"),
    desc: ["edra grey //", "1620x3240mm", "12mm"],
    alt: "mini11",
    url: "edra-grey",
  },
  {
    id: "edra_light",
    img: require("../../../assets/images/colecciones/edra_light.webp"),
    desc: ["edra light //", "1620x3240mm", "12mm"],
    alt: "mini12",
    url: "edra-light",
  },
  {
    id: "edra_sand",
    img: require("../../../assets/images/colecciones/edra_sand.webp"),
    desc: ["edra sand //", "1620x3240mm", "12mm"],
    alt: "mini13",
    url: "edra-sand",
  },
  {
    id: "eme_light_grey",
    img: require("../../../assets/images/colecciones/eme_light_grey.webp"),
    desc: ["eme light grey //", "1620x3240mm", "12mm"],
    alt: "mini14",
    url: "eme-light-grey",
  },
  {
    id: "eme_grey",
    img: require("../../../assets/images/colecciones/eme_grey.webp"),
    desc: ["eme grey //", "1620x3240mm", "12mm"],
    alt: "mini15",
    url: "eme-grey",
  },
  {
    id: "kendo_classic",
    img: require("../../../assets/images/colecciones/kendo_classic.webp"),
    desc: ["kendo classic //", "1620x3240mm", "12mm"],
    alt: "mini16",
    url: "kendo-classic",
  },
  {
    id: "kendo_light",
    img: require("../../../assets/images/colecciones/kendo_light.webp"),
    desc: ["kendo light //", "1620x3240mm", "12mm"],
    alt: "mini17",
    url: "kendo-light",
  },
  {
    id: "noon_grey",
    img: require("../../../assets/images/colecciones/noon_grey.webp"),
    desc: ["noon grey //", "1620x3240mm", "12mm"],
    alt: "mini18",
    url: "noon-grey",
  },
  {
    id: "noon_sand",
    img: require("../../../assets/images/colecciones/noon_sand.webp"),
    desc: ["noon sand //", "1620x3240mm", "12mm"],
    alt: "mini19",
    url: "noon-sand",
  },
  {
    id: "porfido_brown",
    img: require("../../../assets/images/colecciones/porfido_brown.webp"),
    desc: ["pórfido brown //", "1600x3200mm", "12mm"],
    alt: "mini20",
    url: "porfido-brown",
  },
  {
    id: "porfido_sand",
    img: require("../../../assets/images/colecciones/porfido_sand.webp"),
    desc: ["pórfido sand //", "1600x3200mm", "12mm"],
    alt: "mini21",
    url: "porfido-sand",
  },
  {
    id: "wega_black",
    img: require("../../../assets/images/colecciones/wega_black.webp"),
    desc: ["wega black //", "1620x3240mm", "12mm"],
    alt: "mini22",
    url: "wega-black",
  },
];
