export const acabadoObj = {
  id: "acabados",
  headLine: "Finitions //",
  description:
    "Des finitions qui reproduisent la pierre naturelle, la technologie 3d-fit® qui apporte une texture conforme au graphisme, la haute brillance qui apporte profondeur et élégance, la finition naturelle un effet plus fidèle au matériau d'origine ou des surfaces à la finition mate et soyeuse, très résistante.",
  description2: "Cliquez pour voir les différentes finitions",
  description3:
    "Soft / Soft textured / Polished / Natural / Natural S/R / Polished S/R / Matte / Matte S/R / Silk / Hond",
  img_soft: require("../../../assets/images/acabado_soft.webp"),
  img_soft_tx: require("../../../assets/images/acabado_soft_textured.webp"),
  img_pulido: require("../../../assets/images/acabado_pulido.webp"),
  img_natural: require("../../../assets/images/acabado_natural.webp"),
  img_natural_sr: require("../../../assets/images/acabado_natural_sr.webp"),
  img_pulido_sr: require("../../../assets/images/acabado_pulido_sr.webp"),
  img_mate: require("../../../assets/images/acabado_mate.webp"),
  img_mate_sr: require("../../../assets/images/acabado_mate_sr.webp"),
  img_silk: require("../../../assets/images/acabado_silk.webp"),
  img_hond: require("../../../assets/images/acabado_hond.webp"),
  carac_soft: "Soft ",
  carac_soft_tx: "Soft textured ",
  carac_pulido: "Polished ",
  carac_natural: "Natural ",
  carac_natural_sr: "Natural S/R ",
  carac_pulido_sr: "Polished S/R ",
  carac_mate: "Matte ",
  carac_mate_sr: "Matte S/R ",
  carac_silk: "Silk ",
  carac_hond: "Hond ",
  alt: "imagen",
};
