export const Footer = {
  footer: "retour aux collections //",
  footerImg: require("../../../../assets/icons/introduccion/logo.png"),
};
export const PaginasCemento = [
  {
    id: "blue_stone_gris",
    titulo: "blue stone gris //",
    imgL: require("../../../../assets/images/cementos/blue_stone_gris.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/cementos/blue_stone_gris_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/blue_stone_gris.mp4"),
    desc: [
      "mate 1620x3240 mm / 63,7”x127,5”",
      "cemento / concrete / béton",
      "",
    ],
    verimg:
      "haz click en la imagen // click on the picture // cliquez sur l'image",
    vervid: "ver // watch video // regarder la vidéo",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/fr/colecciones/vulcano",
    urlsiguiente: "/fr/colecciones/kron-grey",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "kron_grey",
    titulo: "kron grey //",
    imgL: require("../../../../assets/images/cementos/kron_grey.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/cementos/kron_grey_01.webp"),
    img2: require("../../../../assets/images/cementos/kron_grey_02.webp"),
    imgVid: require("../../../../assets/videos/kron_grey.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "cemento / concrete /béton",
      "2 diseños / 2 designs",
    ],
    verimg:
      "haz click en la imagen // click on the picture // cliquez sur l'image",
    vervid: "ver // watch video // regarder la vidéo ",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/fr/colecciones/blue-stone-gris",
    urlsiguiente: "/fr/colecciones/moma-arena",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "moma_arena",
    titulo: "moma arena //",
    imgL: require("../../../../assets/images/cementos/moma_arena.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/cementos/moma_arena_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/moma_arena.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "cemento / concrete /béton", ""],
    verimg:
      "haz click en la imagen // click on the picture // cliquez sur l'image",
    vervid: "ver // watch video // regarder la vidéo ",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/fr/colecciones/kron-grey",
    urlsiguiente: "/fr/colecciones/moma-gris",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "moma_gris",
    titulo: "moma gris //",
    imgL: require("../../../../assets/images/cementos/moma_gris.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/cementos/moma_gris_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/moma_gris.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "cemento / concrete /béton", ""],
    verimg:
      "haz click en la imagen // click on the picture // cliquez sur l'image",
    vervid: "ver // watch video // regarder la vidéo ",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/fr/colecciones/moma-arena",
    urlsiguiente: "/fr/colecciones/mood-anthracite",
    pdfNombre: "Ficha-Técnica-MomaGris",
    pdfLink: "/downloads/Ficha-Técnica-MomaGris.pdf",
  },
  {
    id: "mood_anthracite",
    titulo: "mood anthracite //",
    imgL: require("../../../../assets/images/cementos/mood_anthracite.webp"),
    img1: require("../../../../assets/images/cementos/mood_anthracite_1.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    imgVid: require("../../../../assets/videos/mood_anthracite.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "micro cemento / micro concrete",
      "2 diseños / 2 designs",
    ],
    verimg: "",
    vervid: "",
    altL: "imagenL",
    altImg1: "//",
    altImg2: "imagen2",
    altVid: "//",
    urlanterior: "/fr/colecciones/moma-gris",
    urlsiguiente: "/fr/colecciones/mood-grey",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "mood_grey",
    titulo: "mood grey //",
    imgL: require("../../../../assets/images/cementos/mood_grey.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/cementos/mood_grey_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/mood_grey.mp4"),
    desc: [
      "soft textured 1620x3240 mm/ 63”x127”",
      "micro cemento / micro concrete",
      " ",
    ],
    verimg:
      "haz click en la imagen // click on the picture // cliquez sur l'image",
    vervid: "ver // watch video // regarder la vidéo ",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/fr/colecciones/mood-anthracite",
    urlsiguiente: "/fr/colecciones/titan-antracita",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "titan_antracita",
    titulo: "titan antracita //",
    imgL: require("../../../../assets/images/cementos/titan_antracita.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/cementos/titan_antracita_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/titan_antracita.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "cemento / concrete /béton", ""],
    verimg:
      "haz click en la imagen // click on the picture // cliquez sur l'image",
    vervid: "ver // watch video // regarder la vidéo ",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/fr/colecciones/mood-grey",
    urlsiguiente: "/fr/colecciones/titan-cemento",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "titan_cemento",
    titulo: "titan cemento //",
    imgL: require("../../../../assets/images/cementos/titan_cemento.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/cementos/titan_cemento_01.webp"),
    img2: require("../../../../assets/images/cementos/imagen_2.webp"),
    imgVid: require("../../../../assets/videos/titan_cemento.mp4"),
    desc: ["mate 1620x3240 mm / 63,7”x127,5”", "cemento / concrete /béton", ""],
    verimg:
      "haz click en la imagen // click on the picture // cliquez sur l'image",
    vervid: "ver // watch video // regarder la vidéo ",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/fr/colecciones/titan-antracita",
    urlsiguiente: "/fr/colecciones/vulcano",
    pdfNombre: "",
    pdfLink: "",
  },

  {
    id: "vulcano",
    titulo: "vulcano //",
    imgL: require("../../../../assets/images/cementos/vulcano.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/cementos/vulcano_01.webp"),
    img2: require("../../../../assets/images/cementos/vulcano_02.webp"),
    imgVid: require("../../../../assets/videos/moma_gris.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "cemento / cement",
      "1 único diseño / 1 single design",
    ],
    verimg:
      "haz click en la imagen // click on the picture // cliquez sur l'image",
    vervid: "ver // watch video // regarder la vidéo ",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/fr/colecciones/mood-grey",
    urlsiguiente: "/fr/colecciones/blue-stone-gris",
    pdfNombre: "",
    pdfLink: "",
  },
];
