import { AnimateSharedLayout } from "framer-motion";

export const Acabados_InfoGeneral = {
  id: "Acabados_InfoGeneral",
  titulo: "Our finishes //",
  subtitulo: [
    "cement and microcement",
    "uniform colors",
    "marble",
    "wood",
    "metal",
    "stone",
  ],
};

export const Acabados_Materiales = [
  {
    id: "allure_anthracite",
    img: require("../../../assets/images/colecciones/allure_anthracite.webp"),
    desc: ["allure anthracite //", "6mm / 1200x2700mm", "12mm / 1620x3240mm"],
    alt: "mini00",
    url: "/bath/allure-anthracite",
  },
  {
    id: "beren_light_grey",
    img: require("../../../assets/images/colecciones/beren_light_grey.webp"),
    desc: ["beren light grey //", "6mm / 1200x2700mm", "12mm / 1620x3240mm"],
    alt: "mini01",
    url: "/bath/beren-light-grey",
  },
  {
    id: "blanc_borghini",
    img: require("../../../assets/images/colecciones/blanc_borghini.webp"),
    desc: ["blanc borghini //", "6mm / 1200x2700mm", "12mm / 1620x3240mm"],
    alt: "mini02",
    url: "/bath/blanc-borghini",
  },
  {
    id: "blanc_invisible",
    img: require("../../../assets/images/colecciones/blanc_invisible.webp"),
    desc: ["blanc invisible //", "6mm / 1200x2700mm", "12mm / 1620x3240mm"],
    alt: "mini03",
    url: "/bath/blanc-invisible",
  },
  {
    id: "brazil_super_white",
    img: require("../../../assets/images/colecciones/brazil_super_white.webp"),
    desc: ["brazil super white //", "6mm / 3000x1200mm", "12mm /1600x3200mm"],
    alt: "mini04",
    url: "/bath/brazil-super-white",
  },
  {
    id: "calacatta",
    img: require("../../../assets/images/colecciones/calacatta.webp"),
    desc: ["calacatta //", "6mm / 1000x3000mm", "12mm / 1620x3240mm"],
    alt: "mini05",
    url: "/bath/calacatta",
  },
  {
    id: "eme_light_grey",
    img: require("../../../assets/images/colecciones/eme_light_grey.webp"),
    desc: ["eme light grey //", "6mm / 1200x2700mm", "12mm / 1620x3240mm"],
    alt: "mini06",
    url: "/bath/eme-light-grey",
  },
  {
    id: "kendo_classic",
    img: require("../../../assets/images/colecciones/kendo_classic.webp"),
    desc: ["kendo classic //", "6mm / 1200x2700mm", "12mm / 1620x3240mm"],
    alt: "mini07",
    url: "/bath/kendo-classic",
  },
  {
    id: "kendo_light",
    img: require("../../../assets/images/colecciones/kendo_light.webp"),
    desc: ["kendo light //", "6mm / 1200x2700mm", "12mm / 1620x3240mm"],
    alt: "mini08",
    url: "/bath/kendo-light",
  },
  {
    id: "moma_gris",
    img: require("../../../assets/images/colecciones/moma_gris.webp"),
    desc: ["moma gris //", "6mm / 1200x3600mm", "12mm / 1620x3240mm"],
    alt: "mini09",
    url: "/bath/moma-gris",
  },
  {
    id: "negro_marquina",
    img: require("../../../assets/images/colecciones/negro_marquina.webp"),
    desc: ["negro marquina //", "6mm / 3000x1000mm", "12mm / 1600x3200mm"],
    alt: "mini10",
    url: "/bath/negro-marquina",
  },
  {
    id: "noon_grey",
    img: require("../../../assets/images/colecciones/noon_grey.webp"),
    desc: ["noon grey //", "6mm / 1200x2700mm", "12mm / 1620x3240mm"],
    alt: "mini11",
    url: "/bath/noon-grey",
  },
  {
    id: "noon_sand",
    img: require("../../../assets/images/colecciones/noon_sand.webp"),
    desc: ["noon sand //", "6mm / 1200x2700mm", "12mm / 1620x3240mm"],
    alt: "mini12",
    url: "/bath/noon-sand",
  },
  {
    id: "paladio",
    img: require("../../../assets/images/colecciones/paladio.webp"),
    desc: ["paladio //", "6mm / 1200x3600mm", "12mm / 1620x3240mm"],
    alt: "mini13",
    url: "/bath/paladio",
  },
  {
    id: "syrac",
    img: require("../../../assets/images/colecciones/syrac.webp"),
    desc: ["syrac //", "6mm / 3000x1200mm", "12mm / 1600x3200mm"],
    alt: "mini14",
    url: "/bath/syrac",
  },
];
