export const Footer = {
  footer: "volver a colecciones //",
  footerImg: require("../../../../assets/icons/introduccion/logo.png"),
};
export const PaginasMadera = [
  {
    id: "canada",
    titulo: "canadá //",
    imgL: require("../../../../assets/images/madera/canada.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/madera/canada_01.webp"),
    imgVid: require("../../../../assets/videos/canada.mp4"),
    desc: [
      "silk 1600x3200 mm/ 63”x126”",
      "madera / wood",
      "1 único diseño / 1 single design",
    ],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altVid: "video",
    urlanterior: "/en/colecciones/irati-abeto",
    urlsiguiente: "/en/colecciones/irati-abeto",
    pdfNombre: "",
    pdfLink: "",
  },
  {
    id: "irati_abeto",
    titulo: "irati abeto //",
    imgL: require("../../../../assets/images/madera/irati_abeto.webp"),
    espesor: require("../../../../assets/icons/espesores/12mm.png"),
    img1: require("../../../../assets/images/madera/irati_abeto_01.webp"),
    img2: require("../../../../assets/images/madera/irati_abeto_02.webp"),
    imgVid: require("../../../../assets/videos/irati_abeto.mp4"),
    desc: ["mate 1600x3200 mm / 63”x126”", "madera / wood", " "],
    verimg: "haz click en la imagen // click on the picture",
    vervid: "ver // watch video",
    altL: "imagenL",
    altImg1: "imagen1",
    altImg2: "imagen2",
    altVid: "video",
    urlanterior: "/en/colecciones/canada",
    urlsiguiente: "/en/colecciones/canada",
    pdfNombre: "",
    pdfLink: "",
  },
];
